version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    environment: 
        - ConnectionString=basketdata
        - EventBusConnection=rabbitmq
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    basketdata:
       image:redis
       expose:
        - "6379"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    environment:
    - ConnectionString=Server=sqldata;Initial Catalog=CatalogData;UserId=sa;Password=12345678
    expose: "80"
    ports: "5101:80"
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

